theme: minima
title: TKS Keeps Secrets
lsi: false
safe: true
incremental: false
hilighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
description: Linux-TKS Main Website
show_downloads: true
plugins:
- jekyll-remote-theme
github_username: valir
rss: rss
authors: "Blog Author"
header_pages:
  - about.md
  - install.md
defaults:
  - scope:
      path: ""
    values:
      author: "Valentin Rusu"

