title: TKS Keeps Secrets
lsi: false
safe: true
incremental: false
hilighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
description: Linux-TKS Main Website
show_downloads: true
plugins:
- jekyll-remote-theme

