remote_theme: jekyll/minima
title: TKS Keeps Secrets
description: This is Linux-TKS' project main website
author:
  name: The Linux-TKS Project
  email: blog@linux-tks.io
baseurl: ""
url: https://linux-tks.io
lsi: false
safe: true
incremental: false
hilighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
show_downloads: true
plugins:
- jekyll-remote-theme
github_username: linux-tks
rss: rss
authors: "Blog Author"
header_pages:
  - about.md
  - install.md
defaults:
  - scope:
      path: ""
    values:
      author: "Valentin Rusu"
minima:
  skin: dark
disqus:
  shortname: linux-tks

